services:
  - type: web
    name: ai-image-classifier
    runtime: python
    plan: free
    buildCommand: |
      python3.10 -m pip install --upgrade pip
      python3.10 -m pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
